// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validação rigorosa - FALHAR EM STARTUP se credenciais não configuradas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = 
    '🚨 ERRO CRÍTICO DE CONFIGURAÇÃO:\n' +
    'Variáveis de ambiente Supabase não encontradas!\n\n' +
    'SOLUÇÃO:\n' +
    '1. Crie arquivo .env.local na raiz do projeto\n' +
    '2. Adicione:\n' +
    '   VITE_SUPABASE_URL=https://seu-projeto.supabase.co\n' +
    '   VITE_SUPABASE_ANON_KEY=sua_chave_anonima\n' +
    '3. Obtenha valores em: https://app.supabase.com/project/[id]/settings/api\n' +
    '\n' +
    'IMPORTANTE: Nunca fazer commit de .env.local!\n';
  
  logger.error(errorMsg);
  throw new Error(errorMsg);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});